version: '3.6'
services:
  mongo:
    container_name: rates_mongo
    image: mongo:4
    restart: always
    volumes:
    - mongodb_vol:/data/db
    networks:
    - rates_services-tier
    ports:
    - 127.0.0.1:27017:27017

  node:
    container_name: rates_node
    restart: always
    depends_on:
    - mongo
    build:
      context: .
      dockerfile: Dockerfile
    networks:
    - rates_services-tier
    ports:
    - $GLS_GATE_HOST:$GLS_GATE_PORT:$GLS_GATE_PORT
    environment:
    - GLS_DAY_START
    - GLS_MONGO_CONNECT
    - GLS_METRICS_HOST
    - GLS_METRICS_PORT
    - GLS_GATE_HOST
    - GLS_GATE_PORT
    - GLS_COIN_MARKET_API_ENDPOINT
    - GLS_COIN_MARKET_API_KEY
    - GLS_FETCH_INTERVAL

volumes:
  mongodb_vol:

networks:
  rates_services-tier:
